import {describe, expect, it} from "vitest";

import * as panda from "../src/index.js";

const EXPECTED_RUNTIME_EXPORTS = [
  "Agent",
  "AgentDocumentTool",
  "AgentError",
  "AgentMemoryContext",
  "BashTool",
  "BraveSearchTool",
  "COMPACT_SUMMARY_PREFIX",
  "ClearEnvValueTool",
  "ConfigurationError",
  "DEFAULT_PANDA_DAEMON_KEY",
  "DEFAULT_PANDA_LLM_CONTEXT_SECTIONS",
  "DateTimeContext",
  "EnvironmentContext",
  "Hook",
  "InvalidJSONResponseError",
  "InvalidSchemaResponseError",
  "LlmContext",
  "MaxTurnsReachedError",
  "MediaTool",
  "OutboundTool",
  "PANDA_DAEMON_HEARTBEAT_INTERVAL_MS",
  "PANDA_DAEMON_REQUEST_TIMEOUT_MS",
  "PANDA_DAEMON_STALE_AFTER_MS",
  "PANDA_PROMPT",
  "PANDA_SUBAGENT_ROLE_POLICIES",
  "PROVIDER_NAMES",
  "PiAiRuntime",
  "PostgresReadonlyQueryTool",
  "RefusalError",
  "RunContext",
  "RunPipeline",
  "ScheduledTaskCancelTool",
  "ScheduledTaskCreateTool",
  "ScheduledTaskUpdateTool",
  "SetEnvValueTool",
  "SpawnSubagentTool",
  "StreamingFailedError",
  "Thread",
  "Tool",
  "ToolError",
  "WebFetchTool",
  "WebResearchTool",
  "WhisperTool",
  "assertProviderName",
  "buildCanonicalModelSelector",
  "buildCompactSummaryMessage",
  "buildPandaLlmContexts",
  "buildPandaTools",
  "createPandaClient",
  "createPandaDaemon",
  "createPandaPool",
  "createPandaRuntime",
  "estimateTokensFromString",
  "filterToolsForSubagentRole",
  "formatParameters",
  "formatProviderNameList",
  "formatToolCallFallback",
  "formatToolResultFallback",
  "gatherContexts",
  "getPandaSubagentRolePolicy",
  "getProviderConfig",
  "hasAnthropicOauthToken",
  "hasOpenAICodexOauthToken",
  "isCompactSummaryMessage",
  "isProviderName",
  "parseProviderName",
  "requirePandaDatabaseUrl",
  "resolveAnthropicAccessToken",
  "resolveCodexHome",
  "resolveDefaultPandaModelSelector",
  "resolveModelSelector",
  "resolveOpenAICodexAuthFilePath",
  "resolveOpenAICodexOauthToken",
  "resolvePandaAgentDir",
  "resolvePandaAgentMediaDir",
  "resolvePandaDatabaseUrl",
  "resolvePandaMediaDir",
  "resolvePandaSkillsDir",
  "resolveProviderApiKey",
  "resolveStoredPandaContext",
  "stringToUserMessage",
  "stripCompactSummaryPrefix",
  "z",
] as const;

const FORBIDDEN_INTERNAL_EXPORTS = [
  "ChannelCursorRepo",
  "ChannelOutboundDeliveryWorker",
  "ChannelTypingDispatcher",
  "ConversationRepo",
  "CredentialCrypto",
  "CredentialResolver",
  "CredentialService",
  "FileSystemMediaStore",
  "HeartbeatRunner",
  "PostgresAgentStore",
  "PostgresCredentialStore",
  "PostgresHomeThreadStore",
  "PostgresIdentityStore",
  "PostgresOutboundDeliveryStore",
  "PostgresScheduledTaskStore",
  "PostgresThreadRuntimeStore",
  "PandaSubagentService",
  "ScheduledTaskRunner",
  "ThreadRuntimeCoordinator",
  "buildTelegramInboundText",
  "buildWhatsAppInboundText",
  "createTelegramTypingAdapter",
  "createWhatsAppOutboundAdapter",
  "ensureReadonlyChatQuerySchema",
  "extractReadableContentFromHtml",
  "fetchReadableWebPage",
  "readDatabaseUsername",
  "summarizeMessageText",
] as const;

describe("package root public API", () => {
  it("matches the intentional runtime export surface", () => {
    expect(Object.keys(panda).sort()).toEqual([...EXPECTED_RUNTIME_EXPORTS]);
  });

  it("does not leak internal domain or integration exports", () => {
    for (const exportName of FORBIDDEN_INTERNAL_EXPORTS) {
      expect(panda).not.toHaveProperty(exportName);
    }
  });
});
