import {describe, expect, it} from "vitest";

import * as panda from "../src/index.js";

const EXPECTED_RUNTIME_EXPORTS = [
  "Agent",
  "AgentPromptTool",
  "AgentError",
  "AgentProfileContext",
  "AgentSkillTool",
  "BashJobCancelTool",
  "BashJobStatusTool",
  "BashJobWaitTool",
  "BashTool",
  "BraveSearchTool",
  "BrowserTool",
  "COMPACT_SUMMARY_PREFIX",
  "ClearEnvValueTool",
  "ConfigurationError",
  "DEFAULT_DAEMON_KEY",
  "DEFAULT_AGENT_LLM_CONTEXT_SECTIONS",
  "DateTimeContext",
  "EnvironmentContext",
  "GlobFilesTool",
  "GrepFilesTool",
  "Hook",
  "InvalidJSONResponseError",
  "InvalidSchemaResponseError",
  "LlmContext",
  "MaxTurnsReachedError",
  "MediaTool",
  "MessageAgentTool",
  "OutboundTool",
  "DAEMON_HEARTBEAT_INTERVAL_MS",
  "DAEMON_REQUEST_TIMEOUT_MS",
  "DAEMON_STALE_AFTER_MS",
  "DEFAULT_AGENT_INSTRUCTIONS",
  "PROVIDER_NAMES",
  "PiAiRuntime",
  "PostgresReadonlyQueryTool",
  "ReadFileTool",
  "RefusalError",
  "RunContext",
  "RunPipeline",
  "ScheduledTaskCancelTool",
  "ScheduledTaskCreateTool",
  "ScheduledTaskUpdateTool",
  "SetEnvValueTool",
  "SpawnSubagentTool",
  "StreamingFailedError",
  "ThinkingSetTool",
  "Thread",
  "Tool",
  "ToolError",
  "WatchCreateTool",
  "WatchDisableTool",
  "WatchSchemaGetTool",
  "WatchUpdateTool",
  "WebFetchTool",
  "WebResearchTool",
  "WhisperTool",
  "WikiTool",
  "assertProviderName",
  "buildBashJobPayload",
  "buildCanonicalModelSelector",
  "buildCompactSummaryMessage",
  "buildDefaultAgentLlmContexts",
  "buildDefaultAgentTools",
  "createRuntimeClient",
  "createDaemon",
  "createPostgresPool",
  "createRuntime",
  "estimateTokensFromString",
  "formatParameters",
  "formatProviderNameList",
  "formatToolCallFallback",
  "formatToolResultFallback",
  "gatherContexts",
  "getProviderConfig",
  "hasAnthropicOauthToken",
  "hasOpenAICodexOauthToken",
  "isCompactSummaryMessage",
  "isProviderName",
  "parseProviderName",
  "requireDatabaseUrl",
  "resolveAnthropicAccessToken",
  "resolveCodexHome",
  "resolveDefaultAgentModelSelector",
  "resolveModelSelector",
  "resolveOpenAICodexAuthFilePath",
  "resolveOpenAICodexOauthToken",
  "resolveAgentDir",
  "resolveAgentMediaDir",
  "resolveDatabaseUrl",
  "resolveMediaDir",
  "resolveProviderApiKey",
  "resolveStoredContext",
  "stringToUserMessage",
  "stripCompactSummaryPrefix",
  "z",
] as const;

const FORBIDDEN_INTERNAL_EXPORTS = [
  "ChannelCursorRepo",
  "ChannelOutboundDeliveryWorker",
  "ChannelTypingDispatcher",
  "ConversationRepo",
  "CredentialCrypto",
  "CredentialResolver",
  "CredentialService",
  "FileSystemMediaStore",
  "HeartbeatRunner",
  "PostgresAgentStore",
  "PostgresCredentialStore",
  "PostgresHomeThreadStore",
  "PostgresIdentityStore",
  "PostgresOutboundDeliveryStore",
  "PostgresScheduledTaskStore",
  "PostgresThreadRuntimeStore",
  "DefaultAgentSubagentService",
  "ScheduledTaskRunner",
  "ThreadRuntimeCoordinator",
  "buildTelegramInboundText",
  "buildWhatsAppInboundText",
  "createTelegramTypingAdapter",
  "createWhatsAppOutboundAdapter",
  "ensureReadonlySessionQuerySchema",
  "extractReadableContentFromHtml",
  "fetchReadableWebPage",
  "readDatabaseUsername",
  "summarizeMessageText",
] as const;

describe("package root public API", () => {
  it("matches the intentional runtime export surface", () => {
    expect(Object.keys(panda).sort()).toEqual([...EXPECTED_RUNTIME_EXPORTS].sort());
  });

  it("does not leak internal domain or integration exports", () => {
    for (const exportName of FORBIDDEN_INTERNAL_EXPORTS) {
      expect(panda).not.toHaveProperty(exportName);
    }
  });
});
