import {describe, expect, it} from "vitest";

import * as panda from "../src/index.js";

const EXPECTED_RUNTIME_EXPORTS = [
  "Agent",
  "AgentError",
  "AgentProfileContext",
  "BackgroundJobCancelTool",
  "BackgroundJobStatusTool",
  "BackgroundJobWaitTool",
  "BashTool",
  "BrowserTool",
  "COMPACT_SUMMARY_PREFIX",
  "CommandCatalogContext",
  "ConfigurationError",
  "DEFAULT_DAEMON_KEY",
  "DEFAULT_AGENT_LLM_CONTEXT_SECTIONS",
  "DEFAULT_AGENT_COMMAND_CATALOG",
  "DEFAULT_AGENT_COMMAND_MODULES",
  "DateTimeContext",
  "EnvironmentContext",
  "Hook",
  "InvalidJSONResponseError",
  "InvalidSchemaResponseError",
  "LlmContext",
  "MaxTurnsReachedError",
  "MediaTool",
  "DAEMON_HEARTBEAT_INTERVAL_MS",
  "DAEMON_REQUEST_TIMEOUT_MS",
  "DAEMON_STALE_AFTER_MS",
  "DEFAULT_AGENT_INSTRUCTIONS",
  "PairedIdentitiesContext",
  "PROVIDER_NAMES",
  "PiAiRuntime",
  "ProviderRuntimeError",
  "RefusalError",
  "RunContext",
  "RunPipeline",
  "SessionPromptsContext",
  "SubagentsContext",
  "StreamingFailedError",
  "ThinkingSetTool",
  "Thread",
  "Tool",
  "ToolError",
  "assertProviderName",
  "agentCommandPolicy",
  "buildBackgroundJobOutput",
  "buildBackgroundJobPayload",
  "buildCanonicalModelSelector",
  "buildCompactSummaryMessage",
  "buildDefaultAgentCommandModules",
  "buildDefaultAgentLlmContexts",
  "buildDefaultAgentTools",
  "createDefaultAgentCommandCatalog",
  "createRuntimeClient",
  "createDaemon",
  "createPostgresPool",
  "createRuntime",
  "estimateTokensFromString",
  "formatParameters",
  "formatProviderNameList",
  "formatToolCallFallback",
  "formatToolResultFallback",
  "gatherContexts",
  "getProviderConfig",
  "hasAnthropicOauthToken",
  "hasOpenAICodexOauthToken",
  "isCompactSummaryMessage",
  "isProviderName",
  "parseProviderName",
  "requireDatabaseUrl",
  "resolveAnthropicAccessToken",
  "resolveCodexHome",
  "resolveDefaultAgentModelSelector",
  "resolveModelSelector",
  "resolveOpenAICodexAuthFilePath",
  "resolveOpenAICodexOauthToken",
  "resolveAgentDir",
  "resolveAgentMediaDir",
  "resolveDatabaseUrl",
  "resolveMediaDir",
  "resolveProviderApiKey",
  "resolveStoredContext",
  "stringToUserMessage",
  "stripCompactSummaryPrefix",
  "z",
] as const;

describe("package root public API", () => {
  it("matches the intentional runtime export surface", () => {
    expect(Object.keys(panda).sort()).toEqual([...EXPECTED_RUNTIME_EXPORTS].sort());
  });
});
