#!/usr/bin/env tsx
import {readFile, writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {buildCommandRouteTree} from "../../src/domain/commands/route-tree.js";
import {DEFAULT_AGENT_COMMAND_SHIM_ROUTES} from "../../src/panda/commands/agent-command-shim-routes.js";
import {DEFAULT_AGENT_COMMAND_DESCRIPTORS} from "../../src/panda/commands/agent-command-descriptors.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const generatedPath = path.join(repoRoot, "scripts/agent-command-shim/routes.generated.sh");
const defaultRouteTree = buildCommandRouteTree({
  routes: DEFAULT_AGENT_COMMAND_SHIM_ROUTES,
  descriptors: DEFAULT_AGENT_COMMAND_DESCRIPTORS,
});

const rootExampleSelections: readonly Array<{
  command: string;
  exampleIndex?: number;
}> = [
  {command: "time.now", exampleIndex: 1},
  {command: "web.fetch", exampleIndex: 0},
  {command: "brave.web.search", exampleIndex: 0},
  {command: "brave.llm.context", exampleIndex: 0},
  {command: "openai.web_research", exampleIndex: 0},
  {command: "watch.create", exampleIndex: 0},
  {command: "watch.runs", exampleIndex: 0},
  {command: "schedule.create", exampleIndex: 0},
  {command: "micro-app.view", exampleIndex: 0},
  {command: "environment.create", exampleIndex: 0},
  {command: "vent.send", exampleIndex: 1},
  {command: "skill.set", exampleIndex: 1},
  {command: "postgres.readonly.query", exampleIndex: 1},
  {command: "wiki.read", exampleIndex: 0},
  {command: "wiki.write.section", exampleIndex: 0},
  {command: "session.prompt.set", exampleIndex: 1},
  {command: "todo.add", exampleIndex: 0},
  {command: "subagent.spawn", exampleIndex: 0},
  {command: "a2a.send", exampleIndex: 0},
  {command: "email.send", exampleIndex: 1},
  {command: "telegram.send", exampleIndex: 1},
  {command: "discord.send", exampleIndex: 1},
  {command: "whatsapp.send", exampleIndex: 1},
  {command: "env.set", exampleIndex: 0},
  {command: "image.generate", exampleIndex: 1},
  {command: "whisper.transcribe", exampleIndex: 1},
  {command: "whisper.translate", exampleIndex: 1},
];

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function helpDelimiter(command: string): string {
  return `PANDA_COMMAND_HELP_${command.replace(/[^A-Za-z0-9_]/g, "_")}`;
}

function jsonHelpDelimiter(command: string): string {
  return `PANDA_COMMAND_HELP_JSON_${command.replace(/[^A-Za-z0-9_]/g, "_")}`;
}

function routeKey(route: {helpArgv: readonly string[]}): string {
  return route.helpArgv.join(" ");
}

function genericLocalUsage(route: {argv: readonly string[]}): string {
  return `panda ${route.argv.join(" ")} --json @payload.json`;
}

function genericLocalHelp(command: string, route: {argv: readonly string[]}): string {
  return [
    `Panda command: ${command}`,
    "",
    "Detailed help is available only through the current agent command lease.",
    "",
    "Usage:",
    `  ${genericLocalUsage(route)}`,
  ].join("\n");
}

function genericLocalHelpJson(command: string, route: {argv: readonly string[]}): unknown {
  return {
    name: command,
    summary: "Detailed help requires current agent command access.",
    description: "Run this help command inside an agent bash call or provide a valid command-access file.",
    usage: genericLocalUsage(route),
    inputModes: ["json"],
    outputModes: ["json"],
    arguments: [],
    examples: [],
  };
}

function rootUsageExamples(): string[] {
  return rootExampleSelections.map(({command, exampleIndex = 0}) => {
    const descriptor = DEFAULT_AGENT_COMMAND_DESCRIPTORS.find((candidate) => candidate.name === command);
    if (!descriptor) {
      throw new Error(`Missing root help example command descriptor: ${command}`);
    }
    const example = descriptor.examples?.[exampleIndex];
    if (!example) {
      throw new Error(`Missing root help example ${exampleIndex} for command descriptor: ${command}`);
    }
    return example.command;
  });
}

function renderGeneratedRoutes(): string {
  const lines = [
    "# Generated by scripts/agent-command-shim/generate-routes.ts. Do not edit.",
    "",
    "agent_command_shim_lookup_route() {",
    "  case \"$1\" in",
  ];

  for (const route of defaultRouteTree.commands) {
    const key = routeKey({helpArgv: route.argv});
    const label = route.argv.join(" ");
    lines.push(
      `    ${shellQuote(key)})`,
      `      printf '%s\\t%s\\n' ${shellQuote(route.command)} ${shellQuote(label)}`,
      "      ;;",
    );
  }

  lines.push(
    "    *)",
    "      return 1",
    "      ;;",
    "  esac",
    "}",
    "",
    "agent_command_shim_print_root_usage_commands() {",
    "  cat <<'PANDA_COMMAND_ROOT_USAGE_COMMANDS'",
  );

  for (const descriptor of DEFAULT_AGENT_COMMAND_DESCRIPTORS) {
    lines.push(`  ${descriptor.usage}`);
  }

  lines.push(
    "PANDA_COMMAND_ROOT_USAGE_COMMANDS",
    "}",
    "",
    "agent_command_shim_print_root_usage_examples() {",
    "  cat <<'PANDA_COMMAND_ROOT_USAGE_EXAMPLES'",
  );

  for (const example of rootUsageExamples()) {
    lines.push(`  ${example}`);
  }

  lines.push(
    "PANDA_COMMAND_ROOT_USAGE_EXAMPLES",
    "}",
    "",
    "agent_command_shim_print_local_help() {",
    "  if declare -F agent_command_shim_has_command_access >/dev/null && agent_command_shim_has_command_access; then",
    "    curl_command \"$(command_url \"/commands/${1}/help\")\"",
    "    return $?",
    "  fi",
    "  case \"$1\" in",
  );

  for (const route of defaultRouteTree.commands) {
    const delimiter = helpDelimiter(route.command);
    lines.push(
      `    ${shellQuote(route.command)})`,
      `      cat <<'${delimiter}'`,
      genericLocalHelp(route.command, route).trimEnd(),
      delimiter,
      "      ;;",
    );
  }

  lines.push(
    "    *)",
    "      return 1",
    "      ;;",
    "  esac",
    "}",
    "",
    "agent_command_shim_print_local_help_json() {",
    "  if declare -F agent_command_shim_has_command_access >/dev/null && agent_command_shim_has_command_access; then",
    "    curl_command \"$(command_url \"/commands/${1}/help?format=json\")\"",
    "    return $?",
    "  fi",
    "  case \"$1\" in",
  );

  for (const route of defaultRouteTree.commands) {
    const delimiter = jsonHelpDelimiter(route.command);
    lines.push(
      `    ${shellQuote(route.command)})`,
      `      cat <<'${delimiter}'`,
      JSON.stringify(genericLocalHelpJson(route.command, route), null, 2),
      delimiter,
      "      ;;",
    );
  }

  lines.push(
    "    *)",
    "      return 1",
    "      ;;",
    "  esac",
    "}",
    "",
  );

  return `${lines.join("\n")}\n`;
}

async function main(): Promise<void> {
  const mode = process.argv.includes("--check") ? "check" : "update";
  const rendered = renderGeneratedRoutes();

  if (mode === "check") {
    const current = await readFile(generatedPath, "utf8").catch(() => "");
    if (current !== rendered) {
      process.stderr.write("Agent command shim generated routes are stale.\n");
      process.stderr.write("Run `pnpm agent-command-shim:update` and commit the updated route fragment.\n");
      process.exitCode = 1;
    }
    return;
  }

  await writeFile(generatedPath, rendered);
  process.stdout.write(`Updated ${path.relative(repoRoot, generatedPath)}\n`);
}

await main();
